<div class="container">

  <!--エラーメッセージ-->
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <%= @contact.errors.count %>件のエラーが発生しました
      <ul>
        <% @contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<h2>お問い合わせ</h2>

<%= form_with model: @contact, url: contacts_path, method: :post, local:true do |f| %>

<div class= "field">
<%= f.label :名前 %><br>
<%= f.text_field :name,size: "40x5" %>
</div>

<div class="field">
<%= f.label :メールアドレス %><br>
<%= f.text_field :email,size: "40x5"%>
</div>
<div class="field">
<%= f.label :電話番号 %><br>
<%= f.text_field :phone_number,size: "40x5" %>
</div>

<div class="field">
<%= f.label :お問い合わせ内容 %><br>
<%= f.text_area :content, size: "40x5" %>
</div>

<div class="field">
<%= f.submit "送信", class: "btn btn-success" %>
</div>

<% end %>
